@startuml
title Deployment for information System
left to right direction
node "<<Смартфон>>" as dk {
  node "<<OS Android/IOS>>" {
      component [.apk (Kobiton)]
  }
}
interface Touch_Screen
interface Microphone
Touch_Screen -- dk
Microphone -- dk
@enduml

